### ISSUE TITLE
Exobrain 말뭉치 라이선스

### ISSUE THREAD

**Issue by sftblw** [kmounlp/NER#5]
파일 중에 파일명이 [엑소브레인](http://exobrain.kr/) 인 파일들이 있는 것 같습니다. 엑소브레인 데이터는 연구 용도가 아니면 상용 사용시 [별도 계약이 필요](http://aiopen.etri.re.kr/service_dataset.php)한 것으로 알고있습니다.

해당 데이터도 MIT 라이선스로 사용해도 문제가 없는지 궁금합니다.

**Comment by aei0109** [comment]
> 파일 중에 파일명이 [엑소브레인](http://exobrain.kr/) 인 파일들이 있는 것 같습니다. 엑소브레인 데이터는 연구 용도가 아니면 상용 사용시 [별도 계약이 필요](http://aiopen.etri.re.kr/service_dataset.php)한 것으로 알고있습니다.
> 
> 해당 데이터도 MIT 라이선스로 사용해도 문제가 없는지 궁금합니다.

-수정됨-
의견 감사합니다.
지적해 주신 부분 인지하였으며,
해당 라이선스는 다음(0b32e06)과 같이 업데이트 되었습니다.

감사합니다.

**Comment by sftblw** [comment]
혹시 엑소브레인인 파일을 제외하고 예외 조항 없이 MIT로 공개해주실수는 없는지 궁금합니다.

(+ 라이선스 수정 커밋은 0b32e066870bda9f65cc190f5e89c2edc6cf8f6d 인 것 같습니다)

**Comment by ho-lol** [comment]
안녕하세요 한국해양대학교 자연언어처리실험실입니다.

연구 목적 이외에 MIT로 공개하는 것은 어려울 것 같습니다.

도움을 드리지 못하여 죄송합니다.
